apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  minReplicas: 1
  maxReplicas: 5 
  metrics:
    - type: Pods
      pods:
        metric:
          name: request_count_total
        target:
          type: AverageValue
          averageValue: 2
