apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: rocketchat
  name: rocketchat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rocketchat
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: rocketchat
    spec:
      containers:
        - env:
            - name: Accounts_UseDNSDomainCheck
              value: "True"
            - name: MONGO_OPLOG_URL
              value: mongodb://mongo:27017/local
            - name: MONGO_URL
              value: mongodb://mongo:27017/rocketchat
            - name: PORT
              value: "3000"
            - name: ROOT_URL
              value: http://chat.badams.ninja
          image: rocket.chat:latest
          name: rocketchat
          ports:
            - containerPort: 3000
          resources: {}
          volumeMounts:
            - mountPath: /app/uploads
              name: rocketchat-claim0
      restartPolicy: Always
      volumes:
        - name: rocketchat-claim0
          persistentVolumeClaim:
            claimName: rocketchat-claim0
status: {}
